export const enum ModelNodeQualifier {
    ALTERNATE = "alternate",
    LEFT = "left",
    MOUNT = "mount",
    RIGHT = "right",
    REAR = "rear",
    SMART = "smart",
    FIRST = "first",
    SECOND = "second",
    THIRD = "third",
    FOURTH = "fourth",
    FIFTH = "fifth",
    SIXTH = "sixth",
    SMALL = "small",
    MEDIUM = "medium",
    LARGE = "large",
    GOLD = "gold",
    RALLY_POINT = "rallypoint",
    EAT_TREE = "eattree",
}
