export const DAMAGE_BONUS_PER_PRIMARY_ATTRIBUTE_POINT = 1

export const MAX_HEALTH_BONUS_PER_STRENGTH_POINT = 25

export const HEALTH_REGENERATION_RATE_BONUS_PER_STRENGTH_POINT = 0.05

export const ARMOR_BONUS_PER_AGILITY_POINT = 0.3

export const MAX_MANA_BONUS_PER_INTELLIGENCE_POINT = 15

export const MANA_REGENERATION_RATE_BONUS_PER_INTELLIGENCE_POINT = 0.05
